/* R254: exam content is fetched only after server authorization. */
'use strict';
const CK_EXAMS=[...[1,2,3,4,5].map(n=>({key:'hsk1-mock-'+n,level:1,kind:'mock',id:n,title:'Đề thi thử HSK1 số '+n,count:40})),...['H21003','H21004','H21006','H21330','H21334'].map((id,i)=>({key:'hsk2-mock-'+id,level:2,kind:'mock',id,title:'Đề thi thử HSK2 số '+(i+1),count:60})),{key:'hsk1-final',level:1,kind:'final',id:'final',title:'Đề cuối khóa HSK1',count:30},{key:'hsk2-final',level:2,kind:'final',id:'final',title:'Đề cuối khóa HSK2',count:60}];
let CK_EXAM_ENTRY_BUSY=false,CK_EXAM_STARTING=false;
let CK_EXAM_RUN=null,CK_EXAM_GENERATION=0,CK_EXAM_TIMER=null,CK_EXAM_POLL=null,CK_EXAM_SAVE=null,CK_EXAM_MEDIA_URLS=[],CK_EXAM_ADMIN=null;
async function ckExamAPI(data,teacher=false,raw=false){const token=teacher?TEACHER_TOKEN:await authToken();if(!token)throw Error('Cần đăng nhập.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),raw?90000:15000);try{const response=await fetch(SB_URL+'/functions/v1/exam-access',{signal:controller.signal,method:'POST',cache:'no-store',headers:{apikey:SB_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok){let d;try{d=await response.json()}catch{}throw Error(d?.error||'Không thể kiểm tra quyền thi. Vui lòng thử lại.');}return raw?response:await response.json();}catch(e){if(e.name==='AbortError')throw Error('Kết nối quá thời gian. Vui lòng thử lại.');throw e;}finally{clearTimeout(timer);}}
function ckExamPage(){let p=document.getElementById('ckSecureExamPage');if(!p){p=document.createElement('section');p.id='ckSecureExamPage';p.className='page h2Page';p.innerHTML='<div class="head"><div><span class="tag">HSK</span><h1 id="ckExamTitle"></h1></div><button class="back" onclick="goBack()">← Quay lại</button></div><div id="ckExamBody"></div>';const host=document.querySelector('.app')||document.querySelector('main')||document.body;host.appendChild(p);installPageHomeButtons();}return p;}
function ckExamClear(){CK_EXAM_GENERATION++;clearInterval(CK_EXAM_TIMER);clearInterval(CK_EXAM_POLL);clearTimeout(CK_EXAM_SAVE);const a=document.getElementById('ckExamAudio');if(a){a.onpause=null;a.onended=null;a.pause();a.removeAttribute('src');a.load();}for(const url of CK_EXAM_MEDIA_URLS)URL.revokeObjectURL(url);CK_EXAM_MEDIA_URLS=[];CK_EXAM_RUN=null;const body=document.getElementById('ckExamBody');if(body)body.replaceChildren();}
function ckExamMessage(message){const el=document.getElementById('ckExamMessage');if(el)el.textContent=message;}
async function ckExamOpen(key){if(!STUDENT_ACCESS_READY){openStudentLogin();return;}ckExamClear();const generation=CK_EXAM_GENERATION,meta=CK_EXAMS.find(x=>x.key===key);if(!meta)return;const page=ckExamPage();page.dataset.examKey=key;document.getElementById('ckExamTitle').textContent=meta.title;openPage('ckSecureExamPage');document.getElementById('ckExamBody').innerHTML='<div class="card ckExamEntryCard"><p>'+meta.count+' câu · '+(meta.kind==='mock'?'Nghe và Đọc · điểm /200':'Kiểm tra cuối khóa')+'</p><p id="ckExamMessage" class="ckExamStatus" role="status" aria-live="polite">Đang kiểm tra quyền thi…</p><div id="ckExamEntry"></div></div>';window.scrollTo(0,0);await ckExamRefreshEntry(generation);if(generation===CK_EXAM_GENERATION&&!CK_EXAM_RUN){clearInterval(CK_EXAM_POLL);CK_EXAM_POLL=setInterval(()=>ckExamRefreshEntry(generation),10000);}}
async function ckExamBegin(key){const generation=CK_EXAM_GENERATION,owner=CK_STUDENT_ID;if(CK_EXAM_STARTING===generation)return;CK_EXAM_STARTING=generation;document.querySelectorAll('#ckExamEntry button').forEach(b=>b.disabled=true);ckExamMessage('Đang mở đề…');try{const d=await ckExamAPI({action:'begin',key});if(generation!==CK_EXAM_GENERATION||owner!==CK_STUDENT_ID)return;if(d.bank)d.bank={...ckExamDisplayBank(d.bank),...CK_EXAMS.find(e=>e.key===key)};CK_EXAM_RUN={...d,key,owner,answers:d.answers||{},audioEnded:false,submitted:false,offset:(d.serverNow||Date.now())-Date.now()};ckExamRender();clearInterval(CK_EXAM_POLL);CK_EXAM_POLL=setInterval(ckExamCheck,10000);}catch(e){if(generation===CK_EXAM_GENERATION){ckExamMessage('🔒 '+e.message);document.querySelectorAll('#ckExamEntry button').forEach(b=>b.disabled=false);}}finally{if(CK_EXAM_STARTING===generation)CK_EXAM_STARTING=false;}}
function ckExamImage(ref){return '<img class="mockSourceImg ckProtectedImage" data-ref="'+esc(ref)+'" alt="Đang tải hình của đề…" decoding="async">';}
function ckExamPictureBank(refs){return '<div class="h2MockPictureBank ckExamPictures">'+refs.map((ref,i)=>'<figure><b>'+String.fromCharCode(65+i)+'</b>'+ckExamImage(ref)+'</figure>').join('')+'</div>';}
function ckExamQuestion(q,i,bank){let content='';if(bank.level===1){content='<b>Câu '+(i+1)+'. '+q.q+'</b>'+(q.img?ckExamImage(q.img):'');}else if(bank.kind==='mock'){let n=i+1,prompt=n<=10?'听录音，判断图片是否正确。':n<=20?'听对话，选择正确的图片。':n<=35?'听对话，选择正确答案。':q.text;content='<b>Câu '+n+'. '+esc(prompt)+'</b>';if(n<=10)content+=ckExamImage(bank.images[n<=5?'judge1':'judge2'][(n-1)%5]);if(n>=11&&n<=20)content+=ckExamPictureBank(bank.images[n<=15?'listen1':'listen2']);if(n>=36&&n<=40)content+=ckExamPictureBank(bank.images.read1);}else{content='<b>Câu '+(i+1)+'. '+esc(q.text||q.q||'')+'</b>';if(q.passage)content+='<p>'+esc(q.passage)+'</p>';if(q.picture)content+=h2Scene(q.picture,'Tranh câu '+(i+1));if(q.pictures)content+='<div class="h2PictureSet">'+q.pictures.map((k,j)=>'<figure><b>'+String.fromCharCode(65+j)+'</b>'+h2Scene(k,'Hình '+String.fromCharCode(65+j))+'</figure>').join('')+'</div>';if(q.audio)content+='<button type="button" class="btn soft ckQuestionAudio" data-index="'+i+'">▶ Nghe câu '+(i+1)+'</button>';}
return '<article class="q '+(q.skill==='listening'?'listenQ':'')+'" id="ckExamQ'+i+'">'+content+'<div class="h2Options">'+q.a.map((a,j)=>'<button type="button" class="opt '+(CK_EXAM_RUN.answers[i]===j?'sel':'')+'" data-question="'+i+'" data-answer="'+j+'">'+ckExamOption(a,j,bank.level===1)+'</button>').join('')+'</div><div class="ex" id="ckExamExplanation'+i+'"></div></article>';}
function ckExamRender(){const run=CK_EXAM_RUN,bank=run.bank;let html=ckExamAudioHeader(run);let skill='';bank.questions.forEach((q,i)=>{if(q.skill&&q.skill!==skill){skill=q.skill;html+='<h2>'+(skill==='listening'?'🎧 Phần Nghe':'📖 Phần Đọc')+'</h2>';}html+=ckExamQuestion(q,i,bank);});html+='<button type="button" class="btn" id="ckExamSubmit" onclick="ckExamSubmit()" '+(bank.kind==='mock'?'disabled':'')+'>Nộp bài thi</button><div id="ckExamResult" role="status"></div><div style="display:flex;justify-content:flex-end;margin-top:24px"><button class="btn soft" onclick="openHSKTests('+bank.level+',false)">Trung tâm kiểm tra HSK'+bank.level+' →</button></div>';document.getElementById('ckExamBody').innerHTML=html;for(const b of document.querySelectorAll('#ckExamBody [data-question]'))b.onclick=()=>ckExamPick(Number(b.dataset.question),Number(b.dataset.answer));for(const b of document.querySelectorAll('.ckQuestionAudio'))b.onclick=()=>{if(!CK_EXAM_RUN||CK_EXAM_RUN!==run)return;speakChinese(bank.questions[Number(b.dataset.index)].audio,'secure-'+b.dataset.index);};ckExamLoadImages();clearInterval(CK_EXAM_TIMER);CK_EXAM_TIMER=setInterval(ckExamTick,1000);ckExamTick();}
function ckExamPick(i,j){const run=CK_EXAM_RUN;if(!run||run.submitted)return;if(run.deadline&&Date.now()+run.offset>=run.deadline)return;run.answers[i]=j;document.querySelectorAll('#ckExamQ'+i+' [data-answer]').forEach(b=>b.classList.toggle('sel',Number(b.dataset.answer)===j));clearTimeout(CK_EXAM_SAVE);CK_EXAM_SAVE=setTimeout(()=>ckExamCheckpoint(run),350);}
async function ckExamCheckpoint(run=CK_EXAM_RUN){if(!run||run.submitted||run.owner!==CK_STUDENT_ID)return;try{await ckExamAPI({action:'checkpoint',attempt:run.attempt,answers:run.answers});}catch(e){if(run===CK_EXAM_RUN)ckExamMessage('Chưa lưu được lựa chọn: '+e.message);}}
async function ckExamLoadImages(){
 const run=CK_EXAM_RUN;if(!run)return;
 // Pinyin is rendered immediately, independently of network image requests.
 if(run.bank.level===2&&run.bank.kind==='mock'){Object.assign(H2_MOCK_RUBY,run.bank.ruby||{});for(const article of document.querySelectorAll('#ckExamBody article')){const n=Number(article.id.replace('ckExamQ',''))+1;if(n>=36)h2MockAddPinyin(article);else article.querySelectorAll('.opt').forEach(h2MockAddPinyin);}}
 const groups=new Map();for(const img of document.querySelectorAll('#ckExamBody .ckProtectedImage:not([src])')){const ref=img.dataset.ref;if(!groups.has(ref))groups.set(ref,[]);groups.get(ref).push(img);}
 const queue=[...groups],workers=Array.from({length:Math.min(4,queue.length)},async()=>{while(queue.length&&run===CK_EXAM_RUN){const [ref,images]=queue.shift();try{const d=await ckExamAPI({action:'media',attempt:run.attempt,ref});if(run!==CK_EXAM_RUN)return;for(const img of images){img.src=d.data;img.alt='Hình của đề';}}catch(e){if(run!==CK_EXAM_RUN)return;for(const img of images)img.alt='Không tải được hình: '+e.message;run.imageError=true;}}});
 await Promise.all(workers);if(run===CK_EXAM_RUN&&run.imageError){ckExamMessage('Có hình chưa tải được. Bấm Tải lại hình để thử lại.');let b=document.getElementById('ckExamRetryImages');if(!b){b=document.createElement('button');b.id='ckExamRetryImages';b.className='btn soft';b.textContent='Tải lại hình';b.onclick=()=>{run.imageError=false;b.remove();ckExamLoadImages();};document.getElementById('ckExamMessage').after(b);}await ckExamCheck();}
}
async function ckExamPlay(){const run=CK_EXAM_RUN;if(!run||run.submitted)return;let b=document.getElementById('ckExamPlay');b.disabled=true;b.textContent='Đang tải audio…';try{const audio=document.getElementById('ckExamAudio');if(!audio.src){const response=await ckExamAPI({action:'media',attempt:run.attempt,ref:run.bank.audioRef},false,true),url=URL.createObjectURL(await response.blob());if(run!==CK_EXAM_RUN){URL.revokeObjectURL(url);return;}CK_EXAM_MEDIA_URLS.push(url);audio.src=url;}const d=await ckExamAPI({action:'audio_start',attempt:run.attempt});if(run!==CK_EXAM_RUN)return;run.deadline=d.deadline;run.offset=d.serverNow-Date.now();run.audioStartedAt=d.audioStartedAt;audio.onended=()=>{run.audioEnded=true;document.getElementById('ckExamSubmit').disabled=false;ckExamAudioStatus();};audio.onpause=()=>{if(!run.submitted&&run===CK_EXAM_RUN&&currentSitePage()==='ckSecureExamPage'&&!audio.ended)audio.play().catch(()=>{b.disabled=false;b.textContent='▶ Tiếp tục audio';});};await audio.play();b.textContent='🎧 Audio đang chạy';ckExamAudioStatus();}catch(e){if(run===CK_EXAM_RUN){b.disabled=false;b.textContent='▶ Thử lại audio';ckExamMessage(e.message);}}}
function ckExamTick(){const run=CK_EXAM_RUN;if(!run||run.submitted||run.bank.kind!=='mock')return;const el=document.getElementById('ckExamClock');if(!run.deadline){if(el)el.textContent='Bắt đầu khi phát audio';return;}const s=Math.max(0,Math.ceil((run.deadline-Date.now()-run.offset)/1000));if(el)el.textContent=Math.floor(s/60)+':'+String(s%60).padStart(2,'0');ckExamAudioStatus();if(!s)ckExamSubmit(true);}
async function ckExamCheck(){const run=CK_EXAM_RUN;if(!run||run.submitted)return;try{await ckExamAPI({action:'check',attempt:run.attempt});}catch(e){if(run!==CK_EXAM_RUN)return;const key=run.key;ckExamClear();await ckExamOpen(key);ckExamMessage('🔒 Quyền thi đã đóng hoặc không thể xác nhận. Nội dung đề đã được thu lại.');}}
async function ckExamSubmit(timeout=false){const run=CK_EXAM_RUN;if(!run||run.busy||run.submitted)return;if(!timeout&&run.bank.kind==='mock'&&!run.audioEnded){ckExamMessage('Audio chưa phát hết. Chưa thể nộp bài.');return;}if(!timeout&&run.bank.questions.some((q,i)=>run.answers[i]===undefined)){ckExamMessage('Em còn câu chưa trả lời. Hãy hoàn thành trước khi nộp.');return;}run.busy=true;document.getElementById('ckExamSubmit').disabled=true;try{await ckExamCheckpoint(run);const d=await ckExamAPI({action:'submit',attempt:run.attempt,answers:run.answers});if(run!==CK_EXAM_RUN||run.owner!==CK_STUDENT_ID)return;run.submitted=true;clearInterval(CK_EXAM_TIMER);clearInterval(CK_EXAM_POLL);const a=document.getElementById('ckExamAudio');if(a){a.onpause=null;a.pause();}ckExamRecord(run,d);ckExamResult(run.key,{...d,answers:run.answers});syncAchievementFromCloud().catch(()=>{});}catch(e){if(run===CK_EXAM_RUN){ckExamMessage(e.message);document.getElementById('ckExamSubmit').disabled=run.bank.kind==='mock'&&!run.audioEnded;}}finally{run.busy=false;}}
function ckExamRecord(run,d){const s=d.result,b=run.bank,history=resultHistory();if(!history.some(x=>x.secureAttempt===run.attempt)){saveResultHistory(b.title,s.score,s.maxScore,s.correct,s.wrong,s.unanswered,b.kind==='mock'?'mock_test':'final_test',{hskLevel:b.level,...s,secureAttempt:run.attempt});let h=resultHistory();const row=h.find(x=>x.secureAttempt===run.attempt);if(row)row.ts=Date.parse(s.completedAt);localStorage.setItem('ck_result_history',JSON.stringify(h));}if(d.reviewBank||d.bank)ckExamStoreReview(d.reviewBank||d.bank,run.answers,run.attempt);}
function ckExamStoreReview(bank,answers,attempt){bank=ckExamDisplayBank(bank);const mark='ck_exam_review_'+attempt;if(localStorage.getItem(mark))return;let wrong=[];bank.questions.forEach((q,i)=>{if(!hskAnswerIsCorrect(q,answers[i])){if(bank.level===2)h2CaptureWrong({kind:bank.kind,id:bank.id,type:bank.kind==='mock'?'mock_test':'final_test',title:bank.title,lesson:null,questions:bank.questions},q,i);else wrong.push({q:q.q,a:q.a[q.ok],e:q.e,options:q.a.slice(),sourceIndex:i});}});if(bank.level===1)recordSmartReview(wrong,{activity:bank.title,type:bank.kind==='mock'?'mock_test':'final_test',hskLevel:1,lessonNumber:null});localStorage.setItem(mark,'1');r237Schedule(true);}
function ckExamResult(key,d){if(d.bank)d.bank=ckExamDisplayBank(d.bank);ckExamClear();const meta=CK_EXAMS.find(x=>x.key===key),s=d.result;let html='<div class="card"><h2>Kết quả: '+s.score+'/'+s.maxScore+'</h2>'+(s.maxScore===200?'<p>'+passEvaluation(meta.title,s.score,s.maxScore)+'</p><p>🎧 Nghe: '+s.listeningScore+'/100 · 📖 Đọc: '+s.readingScore+'/100</p>':'')+'<p>⏱ Thời gian hoàn thành: '+fmtDuration(s.durationSec)+'</p><p>✓ Kết quả đã được lưu trên tài khoản.</p><button class="btn" onclick="openAchievements()">Xem Thành tích của bạn</button><p>'+(!d.release?'Câu sai và lời giải đã được bổ sung vào Ôn tập thông minh. Lời giải toàn đề đang khóa.':'Lời giải đã được giáo viên mở.')+'</p></div>';if(d.bank)html+=d.bank.questions.map((q,i)=>'<div class="q"><b>Câu '+(i+1)+'. '+(meta.level===1?q.q:esc(q.text||''))+'</b><p>'+((d.answers&&hskAnswerIsCorrect(q,d.answers[i]))?'✓ Đúng':'✗ Sai')+' · Đáp án: '+ckExamOption(q.a[q.ok],q.ok,meta.level===1)+'</p><p>'+esc(q.e||'')+'</p></div>').join('');document.getElementById('ckExamBody').innerHTML=html;}
async function ckExamReview(key){const generation=CK_EXAM_GENERATION,owner=CK_STUDENT_ID;try{const d=await ckExamAPI({action:'review',key});if(generation!==CK_EXAM_GENERATION||owner!==CK_STUDENT_ID)return;if((d.reviewBank||d.bank)&&(d.reviewAnswers||d.answers))ckExamStoreReview(d.reviewBank||d.bank,d.reviewAnswers||d.answers,d.attempt);ckExamResult(key,d);}catch(e){if(generation===CK_EXAM_GENERATION)ckExamMessage(e.message);}}
// Teacher UI: server role checks remain authoritative.
async function ckExamAdminLoad(){if(!TEACHER_TOKEN)return;let parent=document.getElementById('teacherLoggedIn');if(!parent)return;let panel=document.getElementById('ckExamAdmin');if(!panel){panel=document.createElement('div');panel.id='ckExamAdmin';panel.className='card';parent.prepend(panel);}panel.innerHTML='<h2>Quản lý quyền thi HSK1–HSK2</h2><p id="ckExamAdminMessage" role="status">Đang tải…</p>';try{CK_EXAM_ADMIN=await ckExamAPI({action:'admin'},true);const data=CK_EXAM_ADMIN;panel.innerHTML='<h2>Quản lý quyền thi HSK1–HSK2</h2><p>Đề được khóa mặc định. Học sinh chỉ được tải câu hỏi, hình và audio khi có quyền thi.</p><form id="ckExamAdminForm"><div class="ckExamAdminFields"><label>Đề thi<select id="ckExamSelect">'+data.exams.map(x=>'<option value="'+esc(x.key)+'">'+esc(x.title)+'</option>').join('')+'</select></label><label>Học sinh<select id="ckExamStudent"><option value="all">Tất cả học sinh</option>'+data.accounts.map(x=>'<option value="'+esc(x.user_id)+'">'+esc(x.student_code+' — '+x.display_name)+'</option>').join('')+'</select></label><label>Mở từ<input type="datetime-local" id="ckExamStart" required></label><label>Đóng lúc<input type="datetime-local" id="ckExamEnd" required></label><label>Số lượt thi<input type="number" id="ckExamAttempts" min="1" max="20" value="1" required></label></div><label><input type="checkbox" id="ckExamRelease"> Cho xem lời giải sau khi nộp bài</label><p id="ckExamAdminMessage" role="status"></p><div style="display:flex;gap:10px;flex-wrap:wrap"><button type="submit" class="btn">Mở đề</button><button type="button" class="btn out" id="ckExamRevokeSelected">Khóa đề</button><button type="button" class="btn soft" id="ckExamReload">Cập nhật</button></div></form><div id="ckExamGrants" style="overflow-x:auto;margin-top:20px"></div>';const localDate=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);document.getElementById('ckExamStart').value=localDate(new Date());document.getElementById('ckExamEnd').value=localDate(new Date(Date.now()+86400000));document.getElementById('ckExamAdminForm').onsubmit=e=>{e.preventDefault();ckExamAdminAction('grant');};document.getElementById('ckExamRevokeSelected').onclick=()=>ckExamAdminAction('revoke');document.getElementById('ckExamReload').onclick=ckExamAdminLoad;document.getElementById('ckExamSelect').onchange=ckExamGrantRows;ckExamGrantRows();}catch(e){panel.querySelector('#ckExamAdminMessage').textContent=e.message;}}
function ckExamGrantRows(){const data=CK_EXAM_ADMIN,key=document.getElementById('ckExamSelect').value,rows=data.grants.filter(g=>g.exam_key===key),now=Date.now();let el=document.getElementById('ckExamGrants');el.innerHTML=rows.length?'<table><thead><tr><th>Học sinh</th><th>Trạng thái</th><th>Thời gian mở</th><th>Lượt được cấp</th><th>Lời giải</th><th>Thao tác</th></tr></thead><tbody>'+rows.map((g,i)=>{const a=data.accounts.find(a=>a.user_id===g.student_id),status=!g.enabled?'Đang khóa':now<Date.parse(g.starts_at)?'Chưa đến giờ':now>=Date.parse(g.ends_at)?'Đã đóng':'Đang mở';return '<tr><td>'+esc(a?a.student_code+' — '+a.display_name:'Tài khoản đã xóa')+'</td><td>'+status+'</td><td>'+esc(new Date(g.starts_at).toLocaleString('vi-VN'))+' – '+esc(new Date(g.ends_at).toLocaleString('vi-VN'))+'</td><td>'+g.attempts_allowed+'</td><td>'+(g.release_solutions?'Đã mở':'Đang khóa')+'</td><td><button type="button" class="btn out" data-revoke="'+i+'">Khóa đề</button> <button type="button" class="btn soft" data-release="'+i+'">'+(g.release_solutions?'Khóa lời giải':'Mở lời giải')+'</button></td></tr>';}).join('')+'</tbody></table>':'<p>Chưa cấp quyền cho đề này.</p>';for(const b of el.querySelectorAll('[data-revoke]'))b.onclick=()=>ckExamAdminAction('revoke',rows[Number(b.dataset.revoke)]);for(const b of el.querySelectorAll('[data-release]'))b.onclick=()=>ckExamAdminAction('release',rows[Number(b.dataset.release)]);}
async function ckExamAdminAction(action,row){const panel=document.getElementById('ckExamAdmin'),message=document.getElementById('ckExamAdminMessage');const selected=document.getElementById('ckExamStudent').value,key=document.getElementById('ckExamSelect').value;let payload={action,key:row?.exam_key||key,students:row?[row.student_id]:selected==='all'?'all':[selected]};if(action==='grant'){const start=new Date(document.getElementById('ckExamStart').value),end=new Date(document.getElementById('ckExamEnd').value);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<=start){message.textContent='Thời gian đóng phải sau thời gian mở.';return;}payload.start=start.toISOString();payload.end=end.toISOString();payload.attempts=Number(document.getElementById('ckExamAttempts').value);payload.release=document.getElementById('ckExamRelease').checked;}if(action==='release')payload.release=!row.release_solutions;panel.querySelectorAll('button').forEach(b=>b.disabled=true);message.textContent='Đang lưu quyền thi…';try{const d=await ckExamAPI(payload,true);await ckExamAdminLoad();document.getElementById('ckExamSelect').value=key;ckExamGrantRows();document.getElementById('ckExamAdminMessage').textContent=(action==='grant'?'Đã mở đề':action==='revoke'?'Đã khóa đề':'Đã cập nhật quyền xem lời giải')+' cho '+d.count+' học sinh.';}catch(e){message.textContent=e.message;panel.querySelectorAll('button').forEach(b=>b.disabled=false);}}
const CK_LOCK_TEACHER_ACCOUNTS=loadTeacherAccounts;loadTeacherAccounts=async function(){const out=await CK_LOCK_TEACHER_ACCOUNTS(...arguments);await ckExamAdminLoad();return out;};
const CK_LOCK_MOCK=startMock;startMock=function(id){return ckExamOpen('hsk1-mock-'+Number(id));};
const CK_LOCK_EXAM=startExam;startExam=function(range){if(range==='final')return ckExamOpen('hsk1-final');return CK_LOCK_EXAM(...arguments);};
const CK_LOCK_H2_START=h2Start;h2Start=function(kind,id){if(kind==='mock'||kind==='final')return ckExamOpen(kind==='mock'?'hsk2-mock-'+id:'hsk2-final');return CK_LOCK_H2_START(...arguments);};
const CK_LOCK_PAGE=openPage;openPage=function(id){if(id!=='ckSecureExamPage'&&document.getElementById('ckSecureExamPage')?.classList.contains('on'))ckExamClear();const out=CK_LOCK_PAGE(...arguments);queueMicrotask(ckExamRefreshCatalog);return out;};
const CK_LOCK_RESTORE=restoreSiteView;restoreSiteView=function(s){if(s.id==='ckSecureExamPage')return ckExamOpen(s.examKey||'hsk1-final');if(s.state&&['mock_test','final_test'].includes(s.state.type))return ckExamOpen(s.state.type==='final_test'?'hsk1-final':'hsk1-mock-'+(s.state.resume?.id||1));if(s.hsk2&&['mock','final'].includes(s.hsk2.kind))return ckExamOpen(s.hsk2.kind==='final'?'hsk2-final':'hsk2-mock-'+s.hsk2.id);const out=CK_LOCK_RESTORE(...arguments);queueMicrotask(ckExamRefreshCatalog);return out;};
const CK_LOCK_CAPTURE=captureSiteView;captureSiteView=function(){let s=CK_LOCK_CAPTURE(...arguments);if(s?.id==='ckSecureExamPage'){s.html=null;s.state=null;s.hsk2=null;s.forms=[];s.audio=[];s.owner=CK_STUDENT_ID;s.examKey=document.getElementById('ckSecureExamPage').dataset.examKey;}return s;};
const CK_LOCK_CACHE=switchStudentCache;switchStudentCache=function(){ckExamClear();return CK_LOCK_CACHE(...arguments);};
const CK_LOCK_LOGOUT=teacherLogout;teacherLogout=async function(){CK_EXAM_ADMIN=null;document.getElementById('ckExamAdmin')?.remove();return CK_LOCK_LOGOUT(...arguments);};
document.addEventListener('visibilitychange',()=>{if(!document.hidden){ckExamCheck();ckExamRefreshEntry();ckExamRefreshCatalog();}});
window.addEventListener('pagehide',ckExamClear);
// Preserve the R250 knowledge/vocabulary routes after recovery.
const CK_R250_CATALOG=h3UpdateCatalogs;h3UpdateCatalogs=function(){const out=CK_R250_CATALOG(...arguments);document.querySelector('#knowledgeGrid .hskLevelCard:nth-child(3)')?.setAttribute('onclick','h3Course()');return out;};
installPageHomeButtons();

const CK_LOCK_RESUME=resumeSavedProgress;resumeSavedProgress=function(){let saved=getResumeProgress();if(saved?.kind==='mock'||saved?.kind==='exam'&&saved.id==='final')return ckExamOpen(saved.kind==='mock'?'hsk1-mock-'+saved.id:'hsk1-final');return CK_LOCK_RESUME(...arguments);};
const CK_LOCK_H2_RESUME=h2Resume;h2Resume=function(){let saved;try{saved=JSON.parse(localStorage.getItem('ck_hsk2_resume')||'null')}catch{}if(saved&&['mock','final'].includes(saved.kind))return ckExamOpen(saved.kind==='mock'?'hsk2-mock-'+saved.id:'hsk2-final');return CK_LOCK_H2_RESUME(...arguments);};

function ckExamGrantMessage(grant,now){if(!grant)return {allowed:false,text:'🔒 Đề chưa được mở cho tài khoản của em. Vui lòng liên hệ giáo viên.'};if(!grant.enabled)return {allowed:false,text:'🔒 Giáo viên đã khóa đề. Em chưa thể xem hoặc làm bài.'};if(now<Date.parse(grant.starts_at))return {allowed:false,text:'⏳ Đề chưa đến giờ mở. Thời gian mở: '+new Date(grant.starts_at).toLocaleString('vi-VN')+'.'};if(now>=Date.parse(grant.ends_at))return {allowed:false,text:'🔒 Đã hết thời gian được mở. Em hãy liên hệ giáo viên nếu cần thêm lượt.'};return {allowed:true,text:'🔓 Đề đã được mở. Bấm Bắt đầu thi khi em đã sẵn sàng.'};}
async function ckExamRefreshEntry(generation=CK_EXAM_GENERATION){const page=document.getElementById('ckSecureExamPage'),key=page?.dataset.examKey,owner=CK_STUDENT_ID;if(!key||CK_EXAM_RUN||(CK_EXAM_ENTRY_BUSY===generation)||(CK_EXAM_STARTING===generation)||currentSitePage()!=='ckSecureExamPage')return;CK_EXAM_ENTRY_BUSY=generation;try{const data=await ckExamAPI({action:'status'});if(generation!==CK_EXAM_GENERATION||owner!==CK_STUDENT_ID||CK_EXAM_RUN||(CK_EXAM_STARTING===generation)||currentSitePage()!=='ckSecureExamPage')return;const grant=data.grants.find(x=>x.exam_key===key),state=ckExamGrantMessage(grant,Number(data.serverNow)||Date.now()),entry=document.getElementById('ckExamEntry');ckExamMessage(state.text);entry.replaceChildren();if(state.allowed){let b=document.createElement('button');b.type='button';b.className='btn';b.textContent='Bắt đầu thi';b.onclick=()=>ckExamBegin(key);entry.append(b);entry.insertAdjacentHTML('beforeend','<p class="muted">Thời gian được mở: '+esc(new Date(grant.starts_at).toLocaleString('vi-VN'))+' – '+esc(new Date(grant.ends_at).toLocaleString('vi-VN'))+'. '+grant.attempts_allowed+' lượt được cấp.</p>');}let retry=document.createElement('button');retry.type='button';retry.className='btn soft';retry.textContent='Cập nhật quyền thi';retry.onclick=()=>ckExamRefreshEntry();entry.append(retry);let review=document.createElement('button');review.type='button';review.className='btn soft';review.textContent='Xem kết quả đã nộp';review.onclick=()=>ckExamReview(key);entry.append(review);ckExamApplyCatalogStatus(data);}catch(e){if(generation===CK_EXAM_GENERATION&&owner===CK_STUDENT_ID&&!CK_EXAM_RUN){ckExamMessage('🔒 Chưa xác nhận được quyền thi: '+e.message+' Em hãy bấm Cập nhật quyền thi để thử lại.');const entry=document.getElementById('ckExamEntry');entry.replaceChildren();const b=document.createElement('button');b.type='button';b.className='btn soft';b.textContent='Cập nhật quyền thi';b.onclick=()=>ckExamRefreshEntry();entry.append(b);}}finally{if(CK_EXAM_ENTRY_BUSY===generation)CK_EXAM_ENTRY_BUSY=false;}}
function ckExamCatalogKey(button){const code=button.getAttribute('onclick')||'';let m=code.match(/startMock\(\s*([1-5])\s*\)/);if(m)return 'hsk1-mock-'+m[1];if(/startExam\(\s*['"]final['"]/.test(code))return 'hsk1-final';m=code.match(/h2Start\(\s*['"]mock['"]\s*,\s*['"]([^'"]+)['"]/);if(m)return 'hsk2-mock-'+m[1];if(/h2Start\(\s*['"]final['"]/.test(code))return 'hsk2-final';return null;}
function ckExamPrepareCatalogStatus(){for(const button of document.querySelectorAll('.page.on button[onclick]')){const key=ckExamCatalogKey(button);if(!key)continue;let card=button.closest('article,.examCard,.h2ExamCard,.lesson,.card')||button.parentElement,badge=card.querySelector('[data-exam-status="'+key+'"]');if(!badge){badge=document.createElement('p');badge.className='ckExamCatalogStatus';badge.dataset.examStatus=key;badge.setAttribute('role','status');badge.textContent='Đang kiểm tra quyền mở đề…';button.before(badge);}}}
function ckExamApplyCatalogStatus(data){if(typeof document==='undefined'||!document)return;const now=Number(data.serverNow)||Date.now();for(const badge of document.querySelectorAll('[data-exam-status]')){const state=ckExamGrantMessage(data.grants.find(g=>g.exam_key===badge.dataset.examStatus),now);badge.textContent=state.text;badge.classList.toggle('isOpen',state.allowed);}}
async function ckExamRefreshCatalog(){if(typeof document==='undefined'||!document||!STUDENT_ACCESS_READY)return;ckExamPrepareCatalogStatus();const badges=[...document.querySelectorAll('.page.on [data-exam-status]')];if(!badges.length)return;const owner=CK_STUDENT_ID;try{const data=await ckExamAPI({action:'status'});if(owner!==CK_STUDENT_ID)return;ckExamApplyCatalogStatus(data);}catch(e){if(owner===CK_STUDENT_ID)for(const badge of badges)if(badge.isConnected)badge.textContent='🔒 Chưa xác nhận được quyền mở đề. Nhấn vào đề để cập nhật.';}}

const CK_EXAM_CATALOG_TIMER=setInterval(ckExamRefreshCatalog,10000);
window.addEventListener('pagehide',()=>clearInterval(CK_EXAM_CATALOG_TIMER));
// Some legacy catalog routes use saved openPage aliases; refresh after the complete catalog render.
for(const name of ['openHSKTests','h2Course','openTestCatalog']){const original=window[name];window[name]=function(){const out=original.apply(this,arguments);queueMicrotask(ckExamRefreshCatalog);return out;};}

// Display-only formatting: retain stable exam keys, question IDs and result ownership.
function ckExamNoCode(value){return String(value??'').replace(/(?:[·•]\s*)?\bH\d{5}\b(?:\s*[·•])?\s*/gi,'').trim();}
function ckExamDisplayBank(bank){const out=structuredClone(bank);out.title=ckExamNoCode(out.title);for(const q of out.questions||[])for(const field of ['q','text','e','imgNote','part'])if(typeof q[field]==='string')q[field]=ckExamNoCode(q[field]);return out;}
function ckExamAudioIntro(bank){return bank.level===2?'Sẵn sàng · Phần Nghe: câu 1–35. Audio chạy liên tục đến hết. Sau phần Nghe có 3 phút điền đáp án, tiếp theo 22 phút làm phần Đọc: câu 36–60.':'Sẵn sàng · Làm câu 1–20 theo audio, sau đó tiếp tục câu 21–40 phần Đọc. Audio chạy liên tục đến hết.';}
function ckExamAudioStatus(){const run=CK_EXAM_RUN;if(!run||run.submitted||!run.audioStartedAt)return;const status=document.getElementById('ckExamAudioStatus');if(!status)return;const message=text=>{status.textContent=text;};const elapsed=(Date.now()+run.offset-Date.parse(run.audioStartedAt))/1000;if(!run.audioEnded){message('Đang thi phần Nghe · Câu 1–'+(run.bank.level===2?35:20)+'. Audio chạy liên tục đến hết.');return;}if(run.bank.level===2&&elapsed<run.audioSeconds+180){const left=Math.max(0,Math.ceil(run.audioSeconds+180-elapsed));message('✓ Đã hoàn thành phần Nghe. Thời gian điền đáp án còn '+Math.floor(left/60)+':'+String(left%60).padStart(2,'0')+'. Sau đó chuyển sang phần Đọc: câu 36–60.');}else message('✓ Đã hoàn thành phần Nghe. Đang thi phần Đọc · Câu '+(run.bank.level===2?'36–60':'21–40')+'.');}
function ckExamCleanVisibleCodes(root){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){return node.parentElement?.closest('script,style,textarea,input,[contenteditable]')?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT;}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes)if(/\bH\d{5}\b/i.test(node.nodeValue))node.nodeValue=ckExamNoCode(node.nodeValue);}
ckExamCleanVisibleCodes(document.body);
const CK_EXAM_CODE_OBSERVER=new MutationObserver(records=>{for(const record of records){if(record.type==='characterData'){const n=record.target;if(!n.parentElement?.closest('script,style,textarea,input,[contenteditable]')&&/\bH\d{5}\b/i.test(n.nodeValue))n.nodeValue=ckExamNoCode(n.nodeValue);}else for(const n of record.addedNodes){if(n.nodeType===1)ckExamCleanVisibleCodes(n);else if(n.nodeType===3&&/\bH\d{5}\b/i.test(n.nodeValue)&&!n.parentElement?.closest('script,style'))n.nodeValue=ckExamNoCode(n.nodeValue);}}});
CK_EXAM_CODE_OBSERVER.observe(document.body,{childList:true,subtree:true,characterData:true});


// The audio heading uses the current catalog title, including resumed older snapshots.
function ckExamAudioHeader(run){const bank=run.bank,meta=CK_EXAMS.find(exam=>exam.key===run.key),title=meta?.title||ckExamNoCode(bank.title);return '<div class="card ckExamAudioCard" style="position:sticky;top:0;z-index:5"><div class="ckExamAudioHeading"><b>'+esc(title)+'</b>'+(bank.kind==='mock'?' · ⏱ <span id="ckExamClock">Bắt đầu khi phát audio</span>':'')+'</div><p id="ckExamMessage" role="status">Đề được mở riêng cho tài khoản của em.</p>'+(bank.kind==='mock'?'<p id="ckExamAudioStatus" role="status">'+ckExamAudioIntro(bank)+'</p><button type="button" class="btn" id="ckExamPlay" onclick="ckExamPlay()">▶ Bắt đầu audio</button><audio id="ckExamAudio" preload="none"></audio>':'')+'</div>';}
