/* R267: private HSK3 mock questions are returned only after authorization. */
'use strict';
CK_EXAMS.push({key:'hsk3-mock-1',level:3,kind:'mock',id:1,title:'Đề thi thử HSK3 số 1',count:80});
const R267_CORRECT=hskAnswerIsCorrect;
hskAnswerIsCorrect=function(q,pick){if(q?.format==='arrange'||q?.format==='hanzi')return typeof pick==='string'&&[q.answer,...(q.alternatives||[])].some(a=>r174Norm(pick)===r174Norm(a));return R267_CORRECT(q,pick);};
const R267_QUESTION=ckExamQuestion;
ckExamQuestion=function(q,i,bank){if(bank.level!==3)return R267_QUESTION(q,i,bank);let content='<b>Câu '+(i+1)+'. '+(q.format==='arrange'?'排列词语，完成句子。':q.format==='hanzi'?esc(q.text||'').replace('（　）','<ruby>（　）<rt>'+esc(q.pinyin)+'</rt></ruby>'):esc(q.text||''))+'</b>'+(q.passage?'<p class="h3Chinese">'+esc(q.passage)+'</p>':'');if(q.imageRefs)content+=ckExamPictureBank(q.imageRefs);let answers='';if(q.format==='arrange')answers='<div class="smartReviewArrange r267ExamTokens">'+q.tokens.map((t,j)=>'<button type="button" class="smartReviewToken" draggable="true" data-r267-token="'+j+'" data-r267-q="'+i+'">'+esc(t)+'</button>').join('')+'</div><div class="smartReviewBuilt r267ExamBuilt" id="r267Built'+i+'" data-r267-drop="'+i+'"></div>';else if(q.format==='hanzi')answers='<input class="smartReviewInput" data-r267-input="'+i+'" maxlength="4" autocomplete="off" aria-label="Câu '+(i+1)+' · điền chữ Hán" value="'+escapeHtmlAttr(CK_EXAM_RUN.answers[i]||'')+'">';else answers='<div class="h2Options">'+q.a.map((a,j)=>'<button type="button" class="opt '+(CK_EXAM_RUN.answers[i]===j?'sel':'')+'" data-question="'+i+'" data-answer="'+j+'">'+ckExamOption(a,j)+'</button>').join('')+'</div>';return '<article class="q '+(q.skill==='listening'?'listenQ':'')+'" id="ckExamQ'+i+'">'+content+answers+'<div class="ex" id="ckExamExplanation'+i+'"></div></article>';};
function r267CanWrite(run){return run===CK_EXAM_RUN&&!run.submitted&&run.owner===CK_STUDENT_ID&&(!run.deadline||Date.now()+run.offset<run.deadline);}
function r267Write(i,value){const run=CK_EXAM_RUN;if(!run||!r267CanWrite(run))return;run.answers[i]=value;clearTimeout(CK_EXAM_SAVE);CK_EXAM_SAVE=setTimeout(()=>ckExamCheckpoint(run),350);}
function r267DrawTokens(i){const run=CK_EXAM_RUN,q=run?.bank.questions[i],built=document.getElementById('r267Built'+i);if(!q||!built)return;const order=run.tokenOrder[i]||[];built.replaceChildren();for(const j of order){const chip=document.createElement('button');chip.type='button';chip.className='smartReviewBuiltToken';chip.textContent=q.tokens[j];chip.onclick=()=>{if(!r267CanWrite(run))return;order.splice(order.indexOf(j),1);r267Write(i,order.map(n=>q.tokens[n]).join(''));r267DrawTokens(i);};built.append(chip);}for(const token of document.querySelectorAll('[data-r267-q="'+i+'"]')){token.hidden=order.includes(Number(token.dataset.r267Token));token.disabled=!r267CanWrite(run);}}
function r267AddToken(i,j){const run=CK_EXAM_RUN;if(!run||!r267CanWrite(run))return;const q=run.bank.questions[i],order=run.tokenOrder[i]||[];if(!q?.tokens||!Number.isInteger(j)||!q.tokens[j]||order.includes(j))return;run.tokenOrder[i]=[...order,j];r267Write(i,run.tokenOrder[i].map(n=>q.tokens[n]).join(''));r267DrawTokens(i);}
const R267_RENDER=ckExamRender;
ckExamRender=function(){const out=R267_RENDER(...arguments),run=CK_EXAM_RUN;if(run?.bank.level!==3)return out;run.tokenOrder=run.tokenOrder||{};for(const [i,q] of run.bank.questions.entries()){if(q.format!=='arrange')continue;if(!run.tokenOrder[i]){let text=r174Norm(run.answers[i]||''),order=[];while(text){const j=q.tokens.findIndex((t,j)=>!order.includes(j)&&text.startsWith(r174Norm(t)));if(j<0)break;order.push(j);text=text.slice(r174Norm(q.tokens[j]).length);}run.tokenOrder[i]=order;}r267DrawTokens(i);}for(const b of document.querySelectorAll('[data-r267-token]')){b.onclick=()=>r267AddToken(Number(b.dataset.r267Q),Number(b.dataset.r267Token));b.ondragstart=e=>e.dataTransfer.setData('text/plain',JSON.stringify({i:Number(b.dataset.r267Q),j:Number(b.dataset.r267Token)}));}for(const box of document.querySelectorAll('[data-r267-drop]')){box.ondragover=e=>e.preventDefault();box.ondrop=e=>{e.preventDefault();try{const x=JSON.parse(e.dataTransfer.getData('text/plain'));if(x.i===Number(box.dataset.r267Drop))r267AddToken(x.i,x.j);}catch{}};}for(const input of document.querySelectorAll('[data-r267-input]'))input.oninput=()=>r267Write(Number(input.dataset.r267Input),input.value);return out;};
const R267_INTRO=ckExamAudioIntro;
ckExamAudioIntro=function(bank){return bank.level===3?'Sẵn sàng · Phần Nghe: câu 1–40. Audio chạy liên tục đến hết. Sau phần Nghe có 5 phút điền đáp án, tiếp theo 30 phút Đọc: câu 41–70 và 15 phút Viết: câu 71–80.':R267_INTRO(bank);};
const R267_STATUS=ckExamAudioStatus;
ckExamAudioStatus=function(){const run=CK_EXAM_RUN;if(run?.bank.level!==3)return R267_STATUS(...arguments);if(!run.audioStartedAt||run.submitted)return;const el=document.getElementById('ckExamAudioStatus');if(!el)return;const elapsed=(Date.now()+run.offset-Date.parse(run.audioStartedAt))/1000,after=elapsed-run.audioSeconds,clock=s=>{const n=Math.ceil(Math.max(0,s));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0')};el.textContent=!run.audioEnded?'Đang thi phần Nghe · Câu 1–40. Audio chạy liên tục đến hết.':after<300?'✓ Đã hoàn thành phần Nghe. Thời gian điền đáp án còn '+clock(300-after)+'. Sau đó chuyển sang phần Đọc: câu 41–70.':after<2100?'Đang thi phần Đọc · Câu 41–70. Thời gian phần Đọc còn '+clock(2100-after)+'. Tiếp theo phần Viết: câu 71–80.':'Đang thi phần Viết · Câu 71–80. Thời gian còn '+clock(3000-after)+'.';};
const R267_OPEN=ckExamOpen;
ckExamOpen=async function(key){const out=await R267_OPEN(...arguments);if(key==='hsk3-mock-1'&&!CK_EXAM_RUN){const intro=document.querySelector('#ckExamBody .ckExamEntryCard > p');if(intro)intro.textContent='80 câu · Nghe, Đọc và Viết · điểm /300';}return out;};
const R267_RESULT=ckExamResult;
ckExamResult=function(key,d){if(key!=='hsk3-mock-1')return R267_RESULT(...arguments);ckExamClear();const s=d.result;let html='<div class="card"><h2>Kết quả: '+s.score+'/'+s.maxScore+'</h2><p>'+passEvaluation('Đề thi thử HSK3 số 1',s.score,s.maxScore)+'</p><div class="h2Score">'+[['Nghe','listening'],['Đọc','reading'],['Viết','writing']].map(([label,k])=>'<div><b>'+s[k+'Score']+'/100</b>'+label+' · '+s[k+'Correct']+'/'+s[k+'Total']+' câu đúng</div>').join('')+'</div><p>'+s.correct+' đúng · '+s.wrong+' sai · '+s.unanswered+' bỏ trống</p><p>⏱ Thời gian hoàn thành: '+fmtDuration(s.durationSec)+'</p><p>✓ Kết quả đã được lưu trên tài khoản.</p><button class="btn" onclick="h3OpenAchievements()">Xem Thành tích của bạn</button><p>'+(d.release?'Lời giải đã được giáo viên mở.':'Câu sai và lời giải đã được bổ sung vào Ôn tập thông minh HSK3. Lời giải toàn đề đang khóa.')+'</p></div>';if(d.bank)html+=d.bank.questions.map((q,i)=>'<div class="q"><b>Câu '+(i+1)+'. '+esc(q.text||'')+'</b>'+(q.passage?'<p>'+esc(q.passage)+'</p>':'')+'<p>'+((d.answers&&hskAnswerIsCorrect(q,d.answers[i]))?'✓ Đúng':'✗ Sai')+' · Đáp án: '+(q.format?esc(q.answer):ckExamOption(q.a[q.ok],q.ok))+'</p><p>'+esc(q.e||'')+'</p></div>').join('');html+='<div class="lessonListReturn"><button class="btn soft" onclick="h3Course(\'tests\')">Trung tâm kiểm tra HSK3 →</button></div>';document.getElementById('ckExamBody').innerHTML=html;};
const R267_CATALOG_KEY=ckExamCatalogKey;
ckExamCatalogKey=function(button){return /ckExamOpen\(\s*['"]hsk3-mock-1['"]/.test(button.getAttribute('onclick')||'')?'hsk3-mock-1':R267_CATALOG_KEY(button);};
const R267_COURSE=h3Course;
h3Course=function(mode='lessons',quick=false){const out=R267_COURSE(...arguments);if(mode==='tests'&&!quick&&currentSitePage()==='hsk3Course'&&!document.getElementById('r267MockCatalog')){document.getElementById('h3CourseBody').insertAdjacentHTML('beforeend','<div class="card" id="r267MockCatalog"><h2>Đề thi thử HSK3</h2><div class="examCards"><article class="examCard"><h3>Đề thi thử HSK3 số 1</h3><p>80 câu · 40 Nghe + 30 Đọc + 10 Viết</p><p>Nghe /100 · Đọc /100 · Viết /100 · Tổng /300</p><p>⏱ Audio nghe, 5 phút điền đáp án, 30 phút Đọc và 15 phút Viết.</p><button class="btn" onclick="ckExamOpen(\'hsk3-mock-1\')">Thi thử</button></article></div></div>');ckExamRefreshCatalog();}return out;};
const R267_TESTS=openHSKTests;
openHSKTests=function(level,quick=false){if(Number(level)===3)return h3Course('tests',quick);return R267_TESTS(...arguments);};
const R267_STORE=ckExamStoreReview;
ckExamStoreReview=function(bank,answers,attempt){R267_STORE(...arguments);if(bank.level!==3)return;const data=r174Read();for(const r of Object.values(data)){if(r.secureAttempt!==attempt)continue;const q=bank.questions.find((q,i)=>Number(q.questionNumber||i+1)===Number(r.questionNumber));if(!q)continue;r.q=(q.passage?q.passage+'\n':'')+(q.text||q.q||'');if(q.format){r.options=[];r.a=q.answer;delete r.answerIndex;r.writingFormat=q.format;r.acceptedAnswers=q.alternatives||[];}r.category=q.skill==='listening'?'Nghe':q.skill==='writing'?'Viết':'Đọc';}r174Write(data);r237Schedule(true);};
const R267_ADMIN_SKILL=adminSkillScore;
adminSkillScore=function(row,skill){if(Number(row.hsk_level)===3&&row.activity_type==='mock_test'){const value=row[skill+'_score'],correct=row[skill+'_correct'],total={listening:40,reading:30,writing:10}[skill];return value==null?'—':'<b>'+Number(value)+'/100</b>'+(correct==null?'':' <small>('+correct+'/'+total+' câu)</small>');}return R267_ADMIN_SKILL(...arguments);};
const R267_SUBMIT=ckExamSubmit;
ckExamSubmit=function(timeout=false){const run=CK_EXAM_RUN;if(!timeout&&run?.bank.level===3&&run.audioEnded&&run.bank.questions.some((q,i)=>q.format&&!r174Norm(run.answers[i]||''))){ckExamMessage('Em còn câu Viết chưa trả lời. Hãy hoàn thành trước khi nộp.');return;}return R267_SUBMIT(...arguments);};
